package com.mayousheng.www.model;

import com.mayousheng.www.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
    public static final News dao = new News().dao();
}
