package com.mayousheng.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return get("id");
    }

    public void setType(java.lang.String type) {
        set("type", type);
    }

    public java.lang.String getType() {
        return get("type");
    }

    public void setTitle(java.lang.String title) {
        set("title", title);
    }

    public java.lang.String getTitle() {
        return get("title");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public void setPicUrl(java.lang.String picUrl) {
        set("picUrl", picUrl);
    }

    public java.lang.String getPicUrl() {
        return get("picUrl");
    }

    public void setUrl(java.lang.String url) {
        set("url", url);
    }

    public java.lang.String getUrl() {
        return get("url");
    }

    public void setCtime(java.util.Date ctime) {
        set("ctime", ctime);
    }

    public java.util.Date getCtime() {
        return get("ctime");
    }

    public void setCreatedAt(java.util.Date createdAt) {
        set("created_at", createdAt);
    }

    public java.util.Date getCreatedAt() {
        return get("created_at");
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        set("updated_at", updatedAt);
    }

    public java.util.Date getUpdatedAt() {
        return get("updated_at");
    }

}
